PRAGMA foreign_keys = ON;

ALTER TABLE os ADD COLUMN grau TEXT DEFAULT 'MEDIA';

UPDATE os
SET grau = CASE UPPER(COALESCE(prioridade, 'MEDIA'))
  WHEN 'BAIXA' THEN 'BAIXA'
  WHEN 'ALTA' THEN 'ALTA'
  WHEN 'EMERGENCIAL' THEN 'CRITICA'
  ELSE 'MEDIA'
END
WHERE grau IS NULL OR TRIM(grau) = '';

CREATE INDEX IF NOT EXISTS idx_os_grau ON os(grau);
