const ROLE = {
  ADMIN: 'ADMIN',
  DIRETORIA: 'DIRETORIA',
  RH: 'RH',
  ENCARREGADO_PRODUCAO: 'ENCARREGADO_PRODUCAO',
  PRODUCAO: 'PRODUCAO',
  MECANICO: 'MECANICO',
  ALMOXARIFADO: 'ALMOXARIFADO',
  COMPRAS: 'COMPRAS',
  MANUTENCAO_SUPERVISOR: 'MANUTENCAO_SUPERVISOR',
  SUPERVISOR_MANUTENCAO: 'SUPERVISOR_MANUTENCAO',
  ENCARREGADO_MANUTENCAO: 'ENCARREGADO_MANUTENCAO',
  GESTAO: 'GESTAO',
};

function normalizeRole(role) {
  const r = String(role || '').trim().toUpperCase();
  if (r === 'DIRECAO') return ROLE.DIRETORIA;
  if (r === 'ALMOXARIFE') return ROLE.ALMOXARIFADO;
  if (r === 'MANUTENCAO') return ROLE.MANUTENCAO_SUPERVISOR;
  if (r === 'SUPERVISOR_MANUTENCAO') return ROLE.MANUTENCAO_SUPERVISOR;
  if (r === 'ENCARREGADO DE MANUTENCAO') return ROLE.ENCARREGADO_MANUTENCAO;
  return r;
}

const ACCESS = {
  painel_operacional: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  pcm: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR],
  equipamentos: [ROLE.ADMIN, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_view: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_open: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_execute: [ROLE.ADMIN, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  preventivas_view: [ROLE.ADMIN, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  preventivas_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR],
  demandas_view: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH],
  demandas_open: [ROLE.ADMIN, ROLE.DIRETORIA],
  demandas_manage: [ROLE.ADMIN],
  solicitacoes: [ROLE.ADMIN, ROLE.ENCARREGADO_PRODUCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR],
  avisos_view: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR],
  avisos_manage: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR],
  almoxarifado: [ROLE.ADMIN, ROLE.ALMOXARIFADO],
  estoque_manage: [ROLE.ADMIN, ROLE.ALMOXARIFADO],
  estoque_view: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.COMPRAS],
  motores: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.MANUTENCAO_SUPERVISOR],
  compras: [ROLE.ADMIN, ROLE.COMPRAS],
  fornecedores: [ROLE.ADMIN, ROLE.COMPRAS, ROLE.GESTAO],
  usuarios: [ROLE.ADMIN],
  escala: [ROLE.ADMIN, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR],
  inspecao_view: [
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.MECANICO,
    ROLE.DIRETORIA,
    ROLE.PRODUCAO,
    ROLE.COMPRAS,
    ROLE.ALMOXARIFADO,
    ROLE.RH,
  ],
  inspecao_edit: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR],
  tracagem_view: [
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.ENCARREGADO_MANUTENCAO,
    ROLE.MECANICO,
    ROLE.GESTAO,
    ROLE.COMPRAS,
    ROLE.ALMOXARIFADO,
  ],
  tracagem_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO],
  desenho_tecnico_view: [
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.ENCARREGADO_MANUTENCAO,
    ROLE.MECANICO,
    ROLE.DIRETORIA,
    ROLE.PRODUCAO,
    ROLE.COMPRAS,
    ROLE.ALMOXARIFADO,
  ],
  desenho_tecnico_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO],
};

function canAccessModule(role, moduleKey) {
  const n = normalizeRole(role);
  if (n === ROLE.ADMIN) return true;
  const allowed = ACCESS[moduleKey] || [];
  return allowed.includes(n);
}

module.exports = { ROLE, ACCESS, normalizeRole, canAccessModule };
